### ISSUE TITLE
Port to other platforms!?

### ISSUE THREAD

**Issue by rraallvv** [rr222cy/BeepPool-Windows-Miner#1]
I've made a [port to macOS](https://github.com/rraallvv/BeepPool-Miner) and I was wondering whether you would want me to make a PR.

Keep up the good work!

**Comment by roos-robert** [comment]
That is awesome @rraallvv ! Absolutely, do that and I will merge everything as soon as possible, great job with the macOS version, I know that a lot of people will appreciate this!
