### ISSUE TITLE
Release packages for MacOS

### ISSUE THREAD

**Issue by roos-robert** [rr222cy/BeepPool-Windows-Miner#4]
Release packages (.zip) files for the MacOS client would be nice, so that users can have the same simple exp. as with the Windows miner.

I have never owned or worked with a Mac so someone more familiar with might be able to contribute here, perhaps it's the same process as on Windows?

**Comment by roos-robert** [comment]
@rraallvv are you able to help out with this? :)

**Comment by rraallvv** [comment]
@rr222cy The macOS version could be build automatically with [Travis](https://docs.travis-ci.com/user/languages/csharp/), for the Window release though, there is [AppVeyor](https://www.appveyor.com/docs/lang/xamarin/). I think I can make a PR with the script and settings to building and deploy the macOS version directly to the repo from Travis.

**Comment by rraallvv** [comment]
@rr222cy [this](https://dotnetcore.gaprogman.com/2017/06/08/continuous-integration-and-appveyor/) also might be of some for AppVeyor .Net builds.
